/**********************************************************************/
/**********************************************************************/
/*****************		Author:  Omar Yahya		***********************/
/*****************		Layer:	 MCAL			***********************/
/*****************		SWC:	 PORT			***********************/
/*****************		File:	 Private        ***********************/
/*****************		Version: 1.00	        ***********************/
/**********************************************************************/
/**********************************************************************/

#ifndef MPORT_MPORT_PRIVATE_H_
#define MPORT_MPORT_PRIVATE_H_

#define INPUT  0
#define OUTPUT 1

#define LOW    0
#define HIGH   1

#define CONC(p7,p6,p5,p4,p3,p2,p1,p0) CONC_HELPER(p7,p6,p5,p4,p3,p2,p1,p0)
#define CONC_HELPER(p7,p6,p5,p4,p3,p2,p1,p0) 0b##p7##p6##p5##p4##p3##p2##p1##p0

#define MPORT_PORTA_DIR CONC(MPORT_PORTA_PIN7_DIR,MPORT_PORTA_PIN6_DIR,MPORT_PORTA_PIN5_DIR,MPORT_PORTA_PIN4_DIR,MPORT_PORTA_PIN3_DIR,MPORT_PORTA_PIN2_DIR,MPORT_PORTA_PIN1_DIR,MPORT_PORTA_PIN0_DIR)
#define MPORT_PORTA_INITIAL_VAL CONC(MPORT_PORTA_PIN7_INITIAL_VAL,MPORT_PORTA_PIN6_INITIAL_VAL,MPORT_PORTA_PIN5_INITIAL_VAL,MPORT_PORTA_PIN4_INITIAL_VAL,MPORT_PORTA_PIN3_INITIAL_VAL,MPORT_PORTA_PIN2_INITIAL_VAL,MPORT_PORTA_PIN1_INITIAL_VAL,MPORT_PORTA_PIN0_INITIAL_VAL)

#define MPORT_PORTB_DIR CONC(MPORT_PORTB_PIN7_DIR,MPORT_PORTB_PIN6_DIR,MPORT_PORTB_PIN5_DIR,MPORT_PORTB_PIN4_DIR,MPORT_PORTB_PIN3_DIR,MPORT_PORTB_PIN2_DIR,MPORT_PORTB_PIN1_DIR,MPORT_PORTB_PIN0_DIR)
#define MPORT_PORTB_INITIAL_VAL CONC(MPORT_PORTB_PIN7_INITIAL_VAL,MPORT_PORTB_PIN6_INITIAL_VAL,MPORT_PORTB_PIN5_INITIAL_VAL,MPORT_PORTB_PIN4_INITIAL_VAL,MPORT_PORTB_PIN3_INITIAL_VAL,MPORT_PORTB_PIN2_INITIAL_VAL,MPORT_PORTB_PIN1_INITIAL_VAL,MPORT_PORTB_PIN0_INITIAL_VAL)

#define MPORT_PORTC_DIR CONC(MPORT_PORTC_PIN7_DIR,MPORT_PORTC_PIN6_DIR,MPORT_PORTC_PIN5_DIR,MPORT_PORTC_PIN4_DIR,MPORT_PORTC_PIN3_DIR,MPORT_PORTC_PIN2_DIR,MPORT_PORTC_PIN1_DIR,MPORT_PORTC_PIN0_DIR)
#define MPORT_PORTC_INITIAL_VAL CONC(MPORT_PORTC_PIN7_INITIAL_VAL,MPORT_PORTC_PIN6_INITIAL_VAL,MPORT_PORTC_PIN5_INITIAL_VAL,MPORT_PORTC_PIN4_INITIAL_VAL,MPORT_PORTC_PIN3_INITIAL_VAL,MPORT_PORTC_PIN2_INITIAL_VAL,MPORT_PORTC_PIN1_INITIAL_VAL,MPORT_PORTC_PIN0_INITIAL_VAL)

#define MPORT_PORTD_DIR CONC(MPORT_PORTD_PIN7_DIR,MPORT_PORTD_PIN6_DIR,MPORT_PORTD_PIN5_DIR,MPORT_PORTD_PIN4_DIR,MPORT_PORTD_PIN3_DIR,MPORT_PORTD_PIN2_DIR,MPORT_PORTD_PIN1_DIR,MPORT_PORTD_PIN0_DIR)
#define MPORT_PORTD_INITIAL_VAL CONC(MPORT_PORTD_PIN7_INITIAL_VAL,MPORT_PORTD_PIN6_INITIAL_VAL,MPORT_PORTD_PIN5_INITIAL_VAL,MPORT_PORTD_PIN4_INITIAL_VAL,MPORT_PORTD_PIN3_INITIAL_VAL,MPORT_PORTD_PIN2_INITIAL_VAL,MPORT_PORTD_PIN1_INITIAL_VAL,MPORT_PORTD_PIN0_INITIAL_VAL)

#endif 
